// Generates TypeScript types for every JSON Schema in contracts/schemas/ (the single source of truth,
// shared with the Python pipeline). `--check` fails when the committed file is stale.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { compile } from "json-schema-to-typescript";
import type { JSONSchema4 } from "json-schema";

const root = join(import.meta.dirname, "../../..");
const schemaDir = join(root, "contracts/schemas");
const outFile = join(root, "web/core/src/generated/contracts.ts");

const names = readdirSync(schemaDir)
  .filter((f) => f.endsWith(".schema.json"))
  .sort();
if (names.length === 0) throw new Error(`no schemas found in ${schemaDir}`);

const parts: string[] = [
  "// GENERATED by web/core/scripts/gen-types.ts from contracts/schemas/ — do not edit.\n",
];
for (const name of names) {
  const schema = JSON.parse(readFileSync(join(schemaDir, name), "utf8")) as JSONSchema4;
  parts.push(
    await compile(schema, name, {
      bannerComment: `// contracts/schemas/${name}`,
      additionalProperties: false,
      strictIndexSignatures: true,
      format: false,
    }),
  );
}
const output = parts.join("\n");

if (process.argv.includes("--check")) {
  const current = readFileSync(outFile, "utf8");
  if (current !== output) {
    console.error("web/core/src/generated/contracts.ts is stale — run `pnpm gen:types`.");
    process.exit(1);
  }
} else {
  writeFileSync(outFile, output);
}
